# This is a basic workflow to help you get started with Actions

# ------------------------------------ #
#       Made By An V.1.0.0           #
# ------------------------------------ #
name: My Python Web
# ------------------------------------ #
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# ------------------------------------ #
jobs:
  metson:
    runs-on: ubuntu-20.04
    continue-on-error: True
    strategy:
      matrix:
        testi: [1.1, 27, 278, 2v, 9e, 93h, os, yys,]
        flaga: [Aqw, his, ]
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runneyr_go
      run: |
        sudo apt update -y && sleep 5
        
  roart-linux:
    needs: [metson]
    runs-on: windows-latest
    continue-on-error: True
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.8]
        check: [2, 4, 8, 10, 12, 14, 16, 18, 20, 22]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: EBroo maov .
      run: |
        cd sd
        ls
        pip install selenium
        pip install names
        python sf.py
  roart-mac:
    needs: [metson]
    runs-on: windows-latest
    continue-on-error: True
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        check: [1, 3, 7, 9, 11, 13, 15, 17, 19, 21]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: EBroo mao ..
      run: |
        cd sd
        ls
        pip install selenium
        pip install names
        python sf.py
